import 'server-only'

/**
 * Read a payslip PDF and work out what is on it (059).
 *
 * WHY THIS EXISTS. These payslips are not authored here — they come out of
 * whatever billing or payroll package the organization already runs, and the
 * admin receives a finished PDF. Re-typing twenty figures off that PDF into the
 * issue dialog is slow and it is the kind of slow that produces wrong numbers,
 * because nobody proofreads their own typing of a deductions table. So the PDF
 * is parsed and the dialog is PREFILLED; the admin then checks it and presses
 * the same Preview and Issue buttons as before.
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │ A SUGGESTION, NEVER A SOURCE OF TRUTH.                                   │
 * │                                                                          │
 * │ Nothing in here is stored, nothing is issued, and nothing is believed    │
 * │ without a person looking at it. Every field comes back with the value    │
 * │ AND a note about how confident the parse was, the dialog says plainly    │
 * │ that it was read off a PDF, and an admin who presses Issue is the one    │
 * │ asserting the figures are right. Every field stays editable.             │
 * │                                                                          │
 * │ That framing is load-bearing. A parser that is quietly trusted turns one │
 * │ misread decimal point into somebody's wrong payslip, and the admin who   │
 * │ could have caught it was never shown the number.                         │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * TEXT EXTRACTION, NOT IMAGE OCR. A payslip generated by software carries a
 * text layer, and reading it is exact — no character confusion, no 8-for-B. A
 * SCANNED payslip is pixels and yields nothing, which is detected and reported
 * as "this looks like a scan" rather than as an empty slip, because those are
 * different problems with different answers (re-export it as a PDF, versus
 * type it in). Running a real OCR model over the image case would mean shipping
 * or calling one, and would produce exactly the figures that must not be
 * trusted silently.
 *
 * HOW THE PARSE WORKS. Payslip layouts differ in everything except one habit:
 * a label on the left and its amount on the right of the same visual line. So
 * the text is split into lines, every line that ends in a number is treated as
 * `label → amount`, and the labels are then classified as earnings or
 * deductions by keyword. Totals are recognised and used as a CHECK rather than
 * as a line, which is what catches a column that was misread.
 */

// The response shape lives in a directive-free module so the payroll dialog can
// describe it without importing this server-only file. See its header.
import type {
  ExtractConfidence, ExtractedLine, ExtractedPayslip,
} from '@/lib/payslip-extracted'

export type { ExtractConfidence, ExtractedLine, ExtractedPayslip }

const MONTHS = [
  'january', 'february', 'march', 'april', 'may', 'june',
  'july', 'august', 'september', 'october', 'november', 'december',
]

/* ------------------------------------------------------- Label vocabulary */

/**
 * Words that mark a line as a DEDUCTION. Checked before the earnings list,
 * because "Professional Tax" and "Income Tax" would otherwise be caught by a
 * generic allowance match.
 */
const DEDUCTION_WORDS = [
  'deduction', 'tax', 'tds', 'pf', 'provident', 'esi', 'esic', ' pt ', 'professional tax',
  'insurance', 'medicare', 'social security', 'withhold', 'loan', 'advance', 'recovery',
  'lop', 'leave without pay', 'contribution', 'nps', 'gratuity recovery', 'federal',
  'state income', 'local income', 'fica', 'garnish', 'premium', '401k', 'roth',
]

/** Words that mark a line as an EARNING. */
const EARNING_WORDS = [
  'basic', 'hra', 'house rent', 'allowance', 'conveyance', 'special', 'medical',
  'bonus', 'incentive', 'commission', 'overtime', 'ot ', 'arrear', 'reimbursement',
  'earning', 'salary', 'wage', 'stipend', 'regular', 'holiday', 'shift', 'leave encashment',
  'cca', 'lta', 'da ', 'dearness', 'gross',
]

/** Lines that are TOTALS, not components — used to check, never added. */
const TOTAL_WORDS = [
  'total', 'gross', 'net pay', 'net salary', 'net amount', 'take home', 'netpay',
  'amount payable', 'net payable',
]

const has = (haystack: string, words: string[]) =>
  words.some((word) => haystack.includes(word))

/**
 * The document's own title, which is never a salary component.
 *
 * Also what `warnings` uses to decide whether this is a payslip at all, so the
 * one pattern serves both and they cannot disagree.
 */
const DOCUMENT_TITLE =
  /pay\s*slip|payslip|salary\s*slip|earnings\s*statement|pay\s*stub|statement\s*of\s*earnings/i

/* ------------------------------------------------------------- Primitives */

/**
 * A number as a payslip writes it: `1,23,456.78`, `1.234,56`, `(500.00)`,
 * `-500`, `₹ 5,000`.
 *
 * THE SEPARATORS ARE THE HARD PART, and getting them wrong moves a decimal
 * point, so the rule is explicit rather than a strip-everything-and-hope:
 *
 *   • Both `.` and `,` present → whichever comes LAST is the decimal point and
 *     the other is grouping. That reads `1,234.56` and `1.234,56` correctly
 *     without needing to know the locale.
 *   • Only `,` → ambiguous. A single comma with one or two digits after it is a
 *     decimal comma (`1234,5`); anything else is grouping (`1,234`, `1,23,456`
 *     — Indian lakh grouping, which is why the group sizes are not validated).
 *   • Only `.` → a single dot is a decimal point; several are grouping.
 *
 * Parentheses mean negative, as they do on every accounting document.
 */
function parseAmount(raw: string): number | null {
  const text = raw.trim()
  if (!text) return null
  const negative = /^\(.*\)$/.test(text) || text.startsWith('-')

  // Everything that is not a digit or a separator goes, including the currency
  // symbol and the sign — the sign is already captured above.
  const body = text.replace(/[^\d.,]/g, '')
  if (!/\d/.test(body)) return null

  const lastDot = body.lastIndexOf('.')
  const lastComma = body.lastIndexOf(',')
  let normalised: string

  if (lastDot >= 0 && lastComma >= 0) {
    const decimalAt = Math.max(lastDot, lastComma)
    const grouping = decimalAt === lastDot ? ',' : '.'
    normalised = `${body.slice(0, decimalAt).split(grouping).join('')}.${body.slice(decimalAt + 1)}`
  } else if (lastComma >= 0) {
    const commas = (body.match(/,/g) ?? []).length
    const decimals = body.length - lastComma - 1
    normalised =
      commas === 1 && decimals >= 1 && decimals <= 2
        ? body.replace(',', '.')
        : body.split(',').join('')
  } else if (lastDot >= 0) {
    const dots = (body.match(/\./g) ?? []).length
    normalised = dots === 1 ? body : body.split('.').join('')
  } else {
    normalised = body
  }

  const value = Number(normalised)
  if (!Number.isFinite(value)) return null
  return negative ? -value : value
}

/**
 * A whitespace-separated numeric token at the END of a line, with whatever came
 * before it.
 *
 * The anchor is `\s` rather than "anything", so `401k` and `01/05/2024` are not
 * mistaken for an amount column — a figure in a table is always separated from
 * its label by space.
 */
const TRAILING_COLUMN = /^(.*?)[\s:\u2026]+(\(?-?[$₹€£]?\s*[\d,.][\d,.]*\)?)$/

/**
 * Split a table row into its label and its numeric COLUMNS, left to right.
 *
 * This is what makes a multi-column layout readable. A US stub prints
 * `Regular  3,200.00  28,800.00` — this period, then year to date — and taking
 * only the last number off that line (which is what the first version of this
 * parser did) reads the year-to-date figure as the period's pay and leaves
 * `Regular 3,200.00` as the label. Peeling every trailing column instead gives
 * a clean label, the period amount from the FIRST column, and the YTD from the
 * last, which is what both layouts mean by that shape.
 *
 * Capped at four columns — rate, hours, this period, year to date is the widest
 * table either layout prints — so a row of a dozen figures is left alone rather
 * than being reduced to a one-word label.
 */
function splitRow(line: string): { label: string; columns: number[] } | null {
  let rest = line
  const columns: number[] = []
  for (let i = 0; i < 4; i += 1) {
    const match = TRAILING_COLUMN.exec(rest)
    if (!match) break
    const amount = parseAmount(match[2])
    if (amount === null) break
    columns.unshift(amount)
    rest = match[1].trim()
  }
  if (!columns.length) return null
  return { label: rest.replace(/[.:\u2026]+$/, '').trim(), columns }
}

/** `Label: value` on one line. */
function fieldAfter(lines: string[], patterns: RegExp[]): string {
  for (const line of lines) {
    for (const pattern of patterns) {
      const match = pattern.exec(line)
      if (match?.[1]) {
        const value = match[1].trim().replace(/^[:\-–—\s]+/, '').trim()
        // A label with nothing after it means the value is on the NEXT line in
        // a two-column layout; that is not something this can read, and an
        // empty string is the honest answer.
        if (value) return value.slice(0, 160)
      }
    }
  }
  return ''
}

/** `04-May-2020`, `04/05/2020`, `2020-05-04` → ISO. Empty when unreadable. */
function toIsoDate(raw: string): string {
  const text = raw.trim()
  let match = /^(\d{4})-(\d{1,2})-(\d{1,2})/.exec(text)
  if (match) {
    return `${match[1]}-${match[2].padStart(2, '0')}-${match[3].padStart(2, '0')}`
  }
  // `04-May-2020` / `4 May 2020`
  match = /^(\d{1,2})[\s\-/]+([A-Za-z]{3,})[\s\-/]+(\d{4})/.exec(text)
  if (match) {
    const month = MONTHS.findIndex((m) => m.startsWith(match![2].toLowerCase().slice(0, 3)))
    if (month >= 0) {
      return `${match[3]}-${String(month + 1).padStart(2, '0')}-${match[1].padStart(2, '0')}`
    }
  }
  // `05/04/2020` — AMBIGUOUS, and deliberately read as US month-first, because
  // that is the only layout in this product that carries explicit period dates.
  match = /^(\d{1,2})[/-](\d{1,2})[/-](\d{4})/.exec(text)
  if (match) {
    const a = Number(match[1])
    const b = Number(match[2])
    // A value over 12 can only be the day, which resolves the ambiguity for
    // most real dates; the rest fall back to month-first.
    const [month, day] = a > 12 ? [b, a] : [a, b]
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${match[3]}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    }
  }
  return ''
}

/** The currency the slip is written in, from its symbol or its code. */
function detectCurrency(text: string): string {
  if (/₹|\bINR\b|\bRs\.?\b/i.test(text)) return 'INR'
  if (/\bUSD\b|\bUS\$/.test(text)) return 'USD'
  if (/\bGBP\b|£/.test(text)) return 'GBP'
  if (/\bEUR\b|€/.test(text)) return 'EUR'
  if (/\bAED\b|د\.إ/.test(text)) return 'AED'
  if (/\bCAD\b|\bC\$/.test(text)) return 'CAD'
  if (/\bAUD\b|\bA\$/.test(text)) return 'AUD'
  if (/\bSGD\b|\bS\$/.test(text)) return 'SGD'
  // A bare `$` last, so `C$`/`A$`/`S$` above win over it.
  if (/\$/.test(text)) return 'USD'
  return ''
}

/** The month and year the slip is FOR, from a "Salary for May 2020" style line. */
function detectPeriod(text: string): { month: number | null; year: number | null } {
  const monthNames = MONTHS.join('|')
  const named = new RegExp(`\\b(${monthNames}|${MONTHS.map((m) => m.slice(0, 3)).join('|')})[a-z]*[\\s,\\-/']+(\\d{4})\\b`, 'i')
  const match = named.exec(text)
  if (match) {
    const key = match[1].toLowerCase().slice(0, 3)
    const month = MONTHS.findIndex((m) => m.startsWith(key))
    if (month >= 0) return { month: month + 1, year: Number(match[2]) }
  }
  // `05/2020` or `2020-05`, as a fallback.
  const numeric = /\b(0?[1-9]|1[0-2])[/-](20\d{2})\b/.exec(text) ?? null
  if (numeric) return { month: Number(numeric[1]), year: Number(numeric[2]) }
  const reversed = /\b(20\d{2})-(0?[1-9]|1[0-2])\b/.exec(text) ?? null
  if (reversed) return { month: Number(reversed[2]), year: Number(reversed[1]) }
  return { month: null, year: null }
}

/* ----------------------------------------------------------------- Parser */

/**
 * Parse already-extracted payslip text.
 *
 * Separate from the PDF reading so it is testable with a string and so the
 * route can report "no text layer" distinctly from "text we could not make
 * sense of".
 */
/**
 * Collapse substrings that PDF renderers duplicate for a bold effect.
 *
 * ADP's PDF overlays the same text 2-6 times at slightly different offsets to
 * simulate bold, and `unpdf` reads all passes concatenated, producing
 * `Gross PayGross PayGross PayGross Pay` instead of `Gross Pay`.
 *
 * Strategy: detect the repetition count from a known marker (e.g.
 * "Earnings Statement" appearing N times in a row), then scan the text for
 * any substring repeated exactly N times and collapse it.
 */
function deduplicateBoldText(text: string): string {
  // Detect the repetition count from known markers.
  const markers = [
    /(?:Earnings Statement){2,6}/,
    /(?:Gross Pay){2,6}/,
    /(?:Net Pay){2,6}/,
    /(?:Pay Date:){2,6}/,
  ]
  let repeatCount = 0
  for (const marker of markers) {
    const match = marker.exec(text)
    if (match) {
      // Find which known phrase repeated
      const phrases = ['Earnings Statement', 'Gross Pay', 'Net Pay', 'Pay Date:']
      for (const phrase of phrases) {
        if (match[0].startsWith(phrase)) {
          repeatCount = match[0].length / phrase.length
          break
        }
      }
      if (repeatCount >= 2) break
    }
  }
  if (repeatCount < 2) return text

  // Now collapse every substring that repeats exactly `repeatCount` times.
  // Build a regex that matches any 2-80 char chunk repeated exactly N times.
  const pattern = new RegExp(`(.{2,80}?)\\1{${repeatCount - 1}}`, 'g')
  return text.replace(pattern, (match, unit) => {
    // Skip trivial repetitions (same character repeated, or single digits).
    if (unit.length <= 1 || new Set(unit).size === 1) return match
    // Verify it's a clean repeat (not a partial overlap).
    if (unit.repeat(repeatCount) !== match) return match
    return unit
  })
}

/**
 * Insert line breaks into text that was extracted as a single blob.
 *
 * Some PDF text extractors (notably `unpdf` on ADP payslips) return the entire
 * page as one line. This inserts `\n` before known structural markers so the
 * parser's per-line logic can work.
 */
function insertLineBreaks(text: string): string {
  // If the text already has a reasonable number of lines, leave it alone.
  const lineCount = text.split('\n').length
  if (lineCount > 5) return text

  // Insert breaks before known payslip section/field markers.
  let result = text
    .replace(/\s+(Period (?:Starting|Ending|Start|End|From|To):)/gi, '\n$1')
    .replace(/\s+(Pay Date:)/gi, '\n$1')
    .replace(/\s+(Employee Name:)/gi, '\n$1')
    .replace(/\s+(Taxable Filing Status:)/gi, '\n$1')
    .replace(/\s+(Exemptions\/Allowances:)/gi, '\n$1')
    .replace(/\s+(Social Security Number:\S*)\s+/gi, '\n$1\n')
    .replace(/\s+(Deposited to the account)/gi, '\n$1')
    .replace(/\s+(Important Notes)/gi, '\n$1')
    .replace(/\s+(Basis of pay:)/gi, '\n$1')
    .replace(/\s+(Your federal taxable)/gi, '\n$1')

  // Insert breaks before earning/deduction table rows: a label followed by
  // numbers. Match `word(s) [-]number` patterns preceded by a space.
  // Key table labels: Regular, Overtime, Gross Pay, Federal Income, etc.
  result = result
    .replace(/\s+((?:Regular|Overtime|Holiday|Bonus|Shift|Incentive)\s+[\d($.,-])/gi, '\n$1')
    .replace(/\s+(Gross Pay\b)/gi, '\n$1')
    .replace(/\s+(Net Pay\b)/gi, '\n$1')
    .replace(/\s+(Federal Income\b)/gi, '\n$1')
    .replace(/\s+(Social Security\b)/gi, '\n$1')
    .replace(/\s+(Medicare\b)/gi, '\n$1')
    .replace(/\s+(State Income\b)/gi, '\n$1')
    .replace(/\s+(Statutory Deductions\b)/gi, '\n$1')
    .replace(/\s+(Earnings\s+rate\b)/gi, '\n$1')
    .replace(/\s+(Deposits\b)/gi, '\n$1')

  return result
}

export function parsePayslipText(raw: string): ExtractedPayslip {
  const text = insertLineBreaks(deduplicateBoldText(raw.replace(/\r/g, '')))
  const lines = text
    .split('\n')
    .map((line) => line.replace(/\s+/g, ' ').trim())
    .filter(Boolean)
  const lower = text.toLowerCase()
  const warnings: string[] = []

  const { month, year } = detectPeriod(text)

  /*
   * MERGE ORPHANED LABELS WITH THEIR NUMBERS.
   *
   * PDF text extraction sometimes puts the label and its numeric columns on
   * separate lines — ADP's fixed-width layout is especially prone to this,
   * producing `Regular\n0.00\n3000.00\n25000.00` instead of one row. A line
   * that is purely alphabetic (a label) followed by one or more purely numeric
   * lines is merged into a single row before the main loop sees it.
   */
  const merged: string[] = []
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    // A label candidate: mostly letters/spaces, no trailing number, and short
    // enough to be a salary component rather than a paragraph.
    if (
      /^[A-Za-z][A-Za-z\s/&\-'.()]+$/.test(line) &&
      line.length <= 40 &&
      !splitRow(line)
    ) {
      // Collect the numeric lines that follow.
      let nums = ''
      let j = i + 1
      while (j < lines.length && /^[\s$₹€£()\d,.\-]+$/.test(lines[j]) && j - i <= 4) {
        nums += ' ' + lines[j]
        j++
      }
      if (nums.trim()) {
        merged.push(line + nums)
        i = j - 1
        continue
      }
    }
    merged.push(line)
  }

  const earnings: ExtractedLine[] = []
  const deductions: ExtractedLine[] = []
  let grossPay: number | null = null
  let netPay: number | null = null

  for (const line of merged) {
    /*
     * The TITLE line is skipped before anything else. `Salary Slip for May
     * 2024` ends in a number and contains the word "salary", so it was being
     * read as a ₹2,024 earnings component — which then threw the gross off by
     * exactly the year.
     */
    if (DOCUMENT_TITLE.test(line)) continue

    const row = splitRow(line)
    if (!row) continue
    const { label, columns } = row
    if (!label || label.length < 2 || label.length > 60) continue
    // A label that is mostly digits is a date, an account number or a column of
    // figures that happened to wrap — not a salary component.
    if ((label.replace(/\D/g, '').length / label.length) > 0.5) continue
    // A prose sentence is not a table row. ADP prints lines like "Your federal
    // taxable wages this period are $3,000.00" which match deduction keywords.
    if (/\b(your|are|is|were|the|this|that|these|those|which|deposited|account)\b/i.test(label) && label.split(/\s+/).length > 4) continue

    /*
     * THIS PERIOD is the second-to-last column, and YEAR TO DATE is the last.
     *
     * A two-column row (`Basic  25,000  25,000`) prints this-period then YTD,
     * so second-to-last IS the first. A three- or four-column row adds rate
     * and hours/units to the LEFT — ADP prints `Regular  0.00  3000.00
     * 25000.00` — so the first column is NOT the period amount. Taking the
     * second-to-last handles both layouts without special-casing.
     */
    const periodIdx = columns.length >= 2 ? columns.length - 2 : 0
    const amount = Math.abs(columns[periodIdx])
    const ytd = columns.length > 1 ? Math.abs(columns[columns.length - 1]) : undefined

    const key = ` ${label.toLowerCase()} `

    // Totals first: they look exactly like components and must not be added to
    // the lines, or the gross would be counted twice.
    if (has(key, TOTAL_WORDS)) {
      if (/net/.test(key)) {
        netPay ??= amount
      } else if (/gross|total earning/.test(key)) {
        grossPay ??= amount
      }
      continue
    }

    if (has(key, DEDUCTION_WORDS)) {
      deductions.push({ label, amount, ytd })
    } else if (has(key, EARNING_WORDS)) {
      earnings.push({ label, amount, ytd })
    }
    // Anything matching neither list is left out rather than guessed into a
    // column. A stray figure in the earnings table changes the net pay.
  }

  const sum = (rows: ExtractedLine[]) =>
    Math.round(rows.reduce((total, row) => total + row.amount, 0) * 100) / 100

  /*
   * THE CROSS-CHECK, and the reason the totals are parsed separately.
   *
   * If the slip prints a gross and the earnings lines do not add up to it, then
   * either a line was missed or something was read into the wrong column —
   * either way the admin needs to know BEFORE they issue it, not after an
   * employee asks why their payslip is short. A pound of tolerance is allowed
   * for rounding between the two.
   */
  const earningsTotal = sum(earnings)
  const deductionsTotal = sum(deductions)
  if (grossPay !== null && earnings.length && Math.abs(earningsTotal - grossPay) > 1) {
    warnings.push(
      `The earnings lines add up to ${earningsTotal.toFixed(2)}, but the slip prints a gross of ${grossPay.toFixed(2)}. Check the earnings before issuing.`
    )
  }
  if (
    netPay !== null &&
    grossPay !== null &&
    Math.abs(grossPay - deductionsTotal - netPay) > 1
  ) {
    warnings.push(
      `Gross minus the deductions found comes to ${(grossPay - deductionsTotal).toFixed(2)}, but the slip prints a net of ${netPay.toFixed(2)}. A deduction may be missing.`
    )
  }
  if (!earnings.length) {
    warnings.push('No earnings lines were recognised — enter the salary components yourself.')
  }

  let employeeName = fieldAfter(lines, [
    /employee\s*name\s*[:\-]?\s*(.+)$/i,
    /\bname\s*of\s*(?:the\s*)?employee\s*[:\-]?\s*(.+)$/i,
    /^name\s*[:\-]\s*(.+)$/i,
  ])
  // ADP-style: the name appears after the SSN marker, either on its own line
  // or inline. Try standalone lines first, then extract from the SSN line or
  // the text immediately following it.
  if (!employeeName) {
    const ssnIdx = lines.findIndex((l) => /social\s*security\s*number|SSN/i.test(l))
    if (ssnIdx >= 0) {
      // Try subsequent lines that are purely a person's name.
      for (let i = ssnIdx + 1; i < Math.min(ssnIdx + 4, lines.length); i++) {
        const candidate = lines[i].trim()
        if (/^[A-Z][a-zA-Z'-]+(?:\s+[A-Z][a-zA-Z'-]+){1,4}$/.test(candidate)) {
          employeeName = candidate
          break
        }
      }
      // If not found as a standalone line, extract from inline text. The name
      // may be on the SSN line itself or on the next line, followed by an
      // address (starting with a digit) or by the company name.
      if (!employeeName) {
        for (let i = ssnIdx; i < Math.min(ssnIdx + 3, lines.length); i++) {
          const src = i === ssnIdx
            ? lines[i].replace(/.*social\s*security\s*number:\s*\S+\s*/i, '')
            : lines[i]
          const nameMatch = /^([A-Z][a-zA-Z'-]+(?:\s+[A-Z][a-zA-Z'-]+){1,4})\s+\d/.exec(src)
          if (nameMatch) {
            employeeName = nameMatch[1].trim()
            break
          }
        }
      }
    }
  }
  const designation = fieldAfter(lines, [
    /designation\s*[:\-]?\s*(.+)$/i,
    /job\s*title\s*[:\-]?\s*(.+)$/i,
    /\bposition\s*[:\-]?\s*(.+)$/i,
  ])
  const employeeCode = fieldAfter(lines, [
    /emp(?:loyee)?\.?\s*(?:id|code|no\.?|number)\s*[:\-]?\s*(\S+)/i,
    /\bassociate\s*id\s*[:\-]?\s*(\S+)/i,
  ])
  const pfNumber = fieldAfter(lines, [
    /\bp\.?\s?f\.?\s*(?:no\.?|number|account)?\s*[:\-]\s*(\S+)/i,
    /\buan\s*[:\-]?\s*(\d[\d\s]*)/i,
  ])
  const bankDetails = fieldAfter(lines, [
    /bank\s*(?:name|details|a\/?c|account)?\s*[:\-]\s*(.+)$/i,
    /\ba\/c\s*(?:no\.?)?\s*[:\-]\s*(.+)$/i,
  ])

  const dateOfJoining = toIsoDate(
    fieldAfter(lines, [
      /date\s*of\s*joining\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
      /\bdoj\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
      /\bjoined\s*(?:on)?\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
    ])
  )
  const periodStart = toIsoDate(
    fieldAfter(lines, [/period\s*(?:start(?:ing)?|from)\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i])
  )
  const periodEnd = toIsoDate(
    fieldAfter(lines, [/period\s*(?:end(?:ing)?|to)\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i])
  )
  const payDate = toIsoDate(
    fieldAfter(lines, [
      /pay\s*date\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
      /payment\s*date\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
      /\bcredited\s*on\s*[:\-]?\s*(\S+(?:\s\S+){0,2})/i,
    ])
  )

  // Pushed BEFORE the confidence is worked out, or a well-parsed invoice would
  // come back as a confident payslip.
  if (!DOCUMENT_TITLE.test(lower)) {
    warnings.push('This does not look like a payslip. Check that the right file was uploaded.')
  }

  /*
   * `low` means "most of this still needs typing", and it is what the dialog
   * uses to decide how loudly to say so. The test is deliberately about whether
   * the MONEY came through: a slip whose name was missed but whose whole
   * earnings table parsed is far more useful than the reverse.
   */
  const confidence: ExtractConfidence =
    earnings.length > 0 && (netPay !== null || grossPay !== null) && warnings.length === 0
      ? 'high'
      : 'low'

  return {
    employeeName,
    designation,
    employeeCode,
    currency: detectCurrency(text),
    month,
    year,
    periodStart,
    periodEnd,
    payDate,
    dateOfJoining,
    pfNumber,
    bankDetails,
    earnings,
    deductions,
    grossPay,
    netPay,
    warnings,
    confidence,
  }
}

/** What went wrong, in terms the admin can act on. */
export type ExtractFailure =
  | { ok: false; reason: 'not_pdf'; message: string }
  | { ok: false; reason: 'no_text'; message: string }
  | { ok: false; reason: 'unreadable'; message: string }

/**
 * Read a payslip PDF.
 *
 * The bytes are never stored. This is a pure transformation from a file the
 * admin already has into a prefilled form, so keeping a copy would add a
 * retention question for no benefit.
 */
export async function extractPayslipFromPdf(
  bytes: Uint8Array
): Promise<{ ok: true; data: ExtractedPayslip } | ExtractFailure> {
  // Magic bytes, not the Content-Type: browsers report whatever the OS registry
  // says, and this is the same rule `src/lib/upload.ts` applies to every upload.
  const header = new TextDecoder().decode(bytes.slice(0, 5))
  if (!header.startsWith('%PDF')) {
    return {
      ok: false,
      reason: 'not_pdf',
      message: 'That is not a PDF. Upload the payslip PDF your payroll software produced.',
    }
  }

  let text = ''
  try {
    const { extractText, getDocumentProxy } = await import('unpdf')
    const pdf = await getDocumentProxy(bytes)
    const extracted = await extractText(pdf, { mergePages: true })
    text = Array.isArray(extracted.text) ? extracted.text.join('\n') : (extracted.text ?? '')
  } catch (err) {
    console.warn('[payslip-extract] could not read the PDF', err)
    return {
      ok: false,
      reason: 'unreadable',
      message: 'That PDF could not be read. It may be password-protected or damaged.',
    }
  }

  // A SCAN, not an empty payslip — and the difference decides what the admin
  // should do next, so it is reported as its own case.
  if (text.replace(/\s/g, '').length < 40) {
    return {
      ok: false,
      reason: 'no_text',
      message:
        'This PDF has no text in it — it looks like a scan or an image. Export the payslip as a PDF from your payroll software, or enter the details below by hand.',
    }
  }

  return { ok: true, data: parsePayslipText(text) }
}
