-- ============================================================================
-- 013_domain_verification.sql
--
-- ONE COMPANY WEBSITE -> ONE WORKSPACE.
--
-- Two people from the same company were signing up independently and ending up
-- with two disconnected workspaces. Email cannot settle it — plenty of real
-- customers run on gmail.com — so the identity we anchor on is the company's
-- own WEBSITE, proven by a token the org publishes on it.
--
-- THE MODEL, and why it is shaped this way:
--
--   • `domain` is a CLAIM. Anyone may claim any domain, and claiming costs
--     nothing. That is deliberate: a unique constraint on the claim would let
--     the first person to type `acme.com` lock the real Acme out of the product
--     forever, which turns a duplicate-prevention feature into a denial of
--     service.
--   • `domain_verified_at` is the PROOF, and only proof is unique. The partial
--     index below is the actual "one company, one workspace" guarantee, and it
--     is enforced by Postgres rather than by a check-then-write in application
--     code that two concurrent requests can both pass.
--   • `domain_token` is the per-tenant secret the org publishes (meta tag or
--     DNS TXT). It is generated by the database, never by the client, and §3
--     below makes it neither readable nor writable from a browser session.
--   • `domain_verify_due_at` is a DEADLINE FOR THE BANNER, not a kill switch.
--
-- Nothing here gates access, before or after the deadline. An unverified
-- workspace keeps working exactly as it does today — it just carries a banner
-- that grows more insistent. Verification is a correctness feature for us, not
-- a paywall for them.
--
-- EVERY ONE OF THE FIVE DOMAIN COLUMNS IS SERVER-OWNED. Two independent
-- mechanisms say so (§3a column privileges, §3b trigger), because this is the
-- feature's only real attack surface: an org that can write
-- `domain_verified_at` has skipped verification entirely.
--
-- Re-runnable: every statement is `if not exists` / `create or replace` / an
-- idempotent grant, so applying this file twice is a no-op.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Columns
-- ---------------------------------------------------------------------------

alter table public.tenants
  -- The host, already normalized by the application: lowercase, no scheme, no
  -- `www.`, no port, no path. Stored bare so two spellings of the same company
  -- can never both hold the verified slot.
  add column if not exists domain text,
  -- Null until proven. This column is the uniqueness key, so it is written by
  -- the server (service role) and by nothing else.
  add column if not exists domain_verified_at timestamptz,
  -- 'meta' (tag on the homepage) or 'dns' (TXT record). Kept for support: "we
  -- found your DNS record, not your tag" answers most of the tickets by itself.
  add column if not exists domain_verification_method text,
  -- The secret to publish. `gen_random_bytes` is volatile, so the ALTER gives
  -- every EXISTING tenant its own distinct token rather than one shared value.
  add column if not exists domain_token text not null default encode(gen_random_bytes(16), 'hex'),
  -- When the workspace is expected to have proven its claim. Nothing is cut off
  -- when it passes — the banner simply stops being polite about it. It is a
  -- stored column rather than `created_at + interval` so that EXISTING
  -- workspaces get a fair window starting the day this migration runs, instead
  -- of being overdue the moment it is applied.
  add column if not exists domain_verify_due_at timestamptz
    not null default (now() + interval '14 days');

/*
 * Shape only — this says "that is a hostname", not "that hostname exists".
 * Every label starts and ends alphanumeric, there is at least one dot, and a
 * bare IPv4 address is refused.
 *
 * Written without lookaround on purpose: Postgres supports lookahead but NOT
 * lookbehind, and the `(?<!-)` spelling of this rule fails to compile.
 */
do $$ begin
  alter table public.tenants
    add constraint tenants_domain_shape_ck check (
      domain is null or (
        length(domain) between 4 and 253
        and domain = lower(domain)
        and domain ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'
        and domain !~ '^[0-9.]+$'
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.tenants
    add constraint tenants_domain_method_ck check (
      domain_verification_method is null
      or domain_verification_method in ('meta', 'dns')
    );
exception when duplicate_object then null; end $$;

-- A verification cannot exist without the domain it verifies.
do $$ begin
  alter table public.tenants
    add constraint tenants_domain_verified_ck check (
      domain_verified_at is null or domain is not null
    );
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- 2. THE guarantee
--
-- Partial on purpose (see the header): unverified claims may collide freely,
-- verified ones may not. A second workspace proving the same domain fails with
-- 23505, which the API turns into "that website is already registered".
-- ---------------------------------------------------------------------------
create unique index if not exists tenants_verified_domain_uq
  on public.tenants (domain)
  where domain_verified_at is not null;

-- Backs the signup pre-check ("is this website already taken?").
create index if not exists tenants_domain_idx on public.tenants (domain)
  where domain is not null;

-- ---------------------------------------------------------------------------
-- 3a. COLUMN PRIVILEGES — the outer wall
--
-- `tenants_update` (002_rls.sql) lets an org update its OWN tenant row, and RLS
-- can express WHICH ROW but not WHICH COLUMN. So a browser session holding a
-- perfectly ordinary org token could `PATCH domain_verified_at = now()` through
-- PostgREST and skip verification entirely.
--
-- The fix is a GRANT, not a policy. Postgres checks column privileges before it
-- ever reaches a policy or a trigger, so a revoked column is not "guarded" —
-- it is invisible to that role. Table-level UPDATE covers every column, and
-- revoking one column does not subtract from it; the only way to express "these
-- columns and no others" is to drop the table grant and re-grant the allowed
-- list. Same pattern as the calendar refresh-token column in 002_rls.sql.
--
-- WRITABLE BY A BROWSER SESSION: exactly what /api/org/settings edits, plus
-- `updated_at` — `tg_set_updated_at` is a plain (invoker-rights) trigger, so
-- without that grant every settings save would fail.
--
-- NOT WRITABLE, ever: id, slug, status, created_at and all five domain columns.
-- Those move only through the service role, behind a handler that has already
-- decided the change is allowed.
-- ---------------------------------------------------------------------------
revoke update on public.tenants from authenticated;
grant update (
  name, logo_url, primary_color, timezone, work_start_time, onboarded_at,
  updated_at,
  address_line1, address_line2, city, state_province, postal_code, country,
  registration_number, company_email, company_phone, website,
  signatory_name, signatory_title, signatory_phone
) on public.tenants to authenticated;

/*
 * READS: everything except the token.
 *
 * `domain_token` is the secret an org publishes to prove ownership, and every
 * member of the workspace — employees included — can read their tenant row.
 * There is no reason for a browser to hold it: the one screen that displays it
 * reads it server-side with the service role. Enumerated rather than "all but
 * one" because Postgres has no such syntax; if you ADD a column to `tenants`,
 * add it here too or client queries selecting it will 403.
 */
revoke select on public.tenants from authenticated;
grant select (
  id, name, slug, logo_url, primary_color, status, timezone, work_start_time,
  onboarded_at, created_at, updated_at,
  address_line1, address_line2, city, state_province, postal_code, country,
  registration_number, company_email, company_phone, website,
  signatory_name, signatory_title, signatory_phone,
  domain, domain_verified_at, domain_verification_method, domain_verify_due_at
) on public.tenants to authenticated;

-- ---------------------------------------------------------------------------
-- 3b. Column guard — the inner wall
--
-- The grants above already make the domain columns unwritable from a session.
-- This trigger is the second, independent layer: it survives someone adding a
-- future `grant update on public.tenants to authenticated`, and it states the
-- rule in the schema where anyone changing this table will read it.
--
-- Same shape as `tg_profiles_guard` (002_rls.sql): a null `auth.uid()` means
-- there is no end user in the request (service role, or a trigger), and those
-- are exactly the paths that legitimately write these columns.
-- ---------------------------------------------------------------------------
create or replace function public.tg_tenants_guard()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  -- Domain identity is server-owned end to end. An org changes its domain
  -- through /api/org/domain, which re-checks availability and resets the proof.
  if new.domain                        is distinct from old.domain
     or new.domain_verified_at         is distinct from old.domain_verified_at
     or new.domain_token               is distinct from old.domain_token
     or new.domain_verification_method is distinct from old.domain_verification_method
     -- Including the deadline: an org that could push its own due date out has
     -- a countdown that means nothing.
     or new.domain_verify_due_at       is distinct from old.domain_verify_due_at then
    raise exception 'Domain verification is managed by the server';
  end if;

  -- Not new rules, just ones that until now lived only in application code.
  if new.id is distinct from old.id or new.slug is distinct from old.slug then
    raise exception 'Workspace identity is immutable';
  end if;
  if new.status is distinct from old.status then
    raise exception 'Workspace status is managed by the platform';
  end if;

  return new;
end;
$$;

drop trigger if exists tenants_guard on public.tenants;
create trigger tenants_guard before update on public.tenants
  for each row execute function public.tg_tenants_guard();

-- ---------------------------------------------------------------------------
-- 4. Carry the signup's domain into the new tenant
--
-- THIS IS 007'S FUNCTION WITH ONE FIELD ADDED, and it has to stay that way.
-- 007 closed a privilege bug by making provisioning require POSITIVE evidence
-- of a self-signup — an `app_role` stamp disqualifies, and a missing `org_name`
-- disqualifies. Re-deriving this from the 003 version (which fell back to the
-- email local-part when `org_name` was absent) would silently reopen that hole,
-- so both guards below are copied forward verbatim. Read 007's header before
-- changing anything above the insert.
--
-- `raw_user_meta_data` is UNTRUSTED (see the trust-boundary note in 003), and
-- that is fine for the domain specifically, because a CLAIM carries no
-- privilege — it is the verification, which this trigger cannot perform, that
-- means anything. The shape check is still applied: a crafted value must not
-- reach the CHECK constraint and abort the whole signup transaction.
-- ---------------------------------------------------------------------------
create or replace function public.provision_tenant_for_org()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_org_name  text;
  v_app_role  text;
  v_domain    text;
  v_tenant_id uuid;
  v_board_id  uuid;
begin
  -- Only org signups, and only when a tenant does not already exist.
  if new.role <> 'org' or new.tenant_id is not null then
    return new;
  end if;

  select nullif(btrim(coalesce(
           u.raw_user_meta_data ->> 'org_name',
           u.raw_user_meta_data ->> 'organization_name',
           ''
         )), ''),
         nullif(u.raw_app_meta_data ->> 'app_role', ''),
         nullif(btrim(lower(coalesce(u.raw_user_meta_data ->> 'org_domain', ''))), '')
    into v_org_name, v_app_role, v_domain
    from auth.users u
   where u.id = new.id;

  -- (007) An account stamped with any app_role is admin-created and never a
  -- self-signup, even if this row currently reads 'org' because the stamp
  -- landed late.
  if v_app_role is not null and v_app_role <> 'org' then
    return new;
  end if;

  -- (007) THE GUARD THAT CLOSES THE HOLE. signUp() writes org_name in the same
  -- INSERT, so a genuine self-signup always has it; an admin-created account
  -- never does. Absence of data must not grant a workspace.
  if v_org_name is null then
    return new;
  end if;

  -- Anything that would not satisfy the CHECK is dropped rather than allowed to
  -- fail the signup. The banner asks the org for it again on first sign-in.
  if v_domain is not null
     and (length(v_domain) > 253
          or v_domain !~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'
          or v_domain ~ '^[0-9.]+$') then
    v_domain := null;
  end if;

  insert into public.tenants (name, slug, domain, website)
  values (
    left(v_org_name, 120),
    public.tenant_slug_from(v_org_name),
    v_domain,
    -- Seeds the letterhead's display website too, so nobody retypes it.
    v_domain
  )
  returning id into v_tenant_id;

  update public.profiles
     set tenant_id = v_tenant_id,
         role      = 'org'
   where id = new.id;

  -- Seed the default Kanban board so the workspace is never an empty shell.
  insert into public.boards (tenant_id, name, created_by)
  values (v_tenant_id, 'Team Board', new.id)
  returning id into v_board_id;

  insert into public.board_columns (tenant_id, board_id, name, position)
  values
    (v_tenant_id, v_board_id, 'To Do',       0),
    (v_tenant_id, v_board_id, 'In Progress', 1),
    (v_tenant_id, v_board_id, 'Done',        2);

  insert into public.audit_logs (tenant_id, actor_id, actor_email, action, entity, entity_id, meta)
  values (v_tenant_id, new.id, new.email::text, 'tenant.provisioned', 'tenants', v_tenant_id,
          jsonb_build_object('name', v_org_name, 'domain', v_domain));

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. current_profile() gains the two fields the banner needs
--
-- DROP first: `create or replace` cannot change a function's return type, and
-- this one returns a fixed column list.
--
-- `domain_token` is deliberately NOT here. It is a secret the org publishes on
-- request, read on one page by one handler; putting it in the context that
-- every page render already carries would spread it across the whole app for no
-- reason.
-- ---------------------------------------------------------------------------
drop function if exists public.current_profile();

create or replace function public.current_profile()
returns table (
  id uuid,
  tenant_id uuid,
  role text,
  full_name text,
  email text,
  photo_url text,
  is_active boolean,
  must_change_password boolean,
  department_id uuid,
  tenant_name text,
  tenant_slug text,
  tenant_status text,
  tenant_logo_url text,
  tenant_primary_color text,
  tenant_timezone text,
  tenant_work_start_time text,
  tenant_onboarded boolean,
  tenant_domain text,
  tenant_domain_verified boolean,
  tenant_domain_due_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select p.id, p.tenant_id, p.role::text, p.full_name, p.email::text, p.photo_url,
         p.is_active, p.must_change_password, p.department_id,
         t.name, t.slug, t.status::text, t.logo_url, t.primary_color, t.timezone,
         to_char(t.work_start_time, 'HH24:MI'),
         (t.onboarded_at is not null),
         t.domain,
         (t.domain_verified_at is not null),
         t.domain_verify_due_at
    from public.profiles p
    left join public.tenants t on t.id = p.tenant_id
   where p.id = auth.uid();
$$;

revoke execute on function public.current_profile() from anon, public;
grant execute on function public.current_profile() to authenticated, service_role;
