import { describe, it, expect } from 'vitest'
import webpush from 'web-push'
import { publicKeyProblem, privateKeyProblem } from '@/lib/push/vapid'
import { pushSubscriptionSchema, pushUnsubscribeSchema } from '@/lib/schemas'
import { importanceFor, pathFor, tagFor } from '@/lib/notifications/events'

/**
 * The notification system's two silent failure modes, pinned down.
 *
 * Both are the kind that report success and deliver nothing, which is why they
 * are worth tests rather than a careful reading:
 *
 *   1. A MALFORMED VAPID KEY. Every push signed with it is refused by the push
 *      service with a 403, one per device per notification, forever — while the
 *      product's own logs show a notification raised and a row written. The only
 *      place this can be caught is at the point the key is accepted.
 *
 *   2. AN ENDPOINT THAT IS NOT A PUSH SERVICE. `endpoint` becomes the URL the
 *      server makes an outbound request to on every notification. Left
 *      unvalidated it is a server-side request forgery primitive with a built-in
 *      reporting channel — the delivery ledger faithfully records what the
 *      internal address answered.
 */

// A real pair, generated by scripts/push-keys.ts. Safe to commit: it is used
// nowhere, and a VAPID public key is public by construction anyway.
const VALID_PUBLIC =
  'BFwGquH27uJge9glYgKpKEftsepTUnkCM1t8eFgBwdNV_DeUkmAowYgkXpKvLoyF-8WLf0oJqnlZyn0ngtrZzNU'
const VALID_PRIVATE = 'kBAomnQ_Py7CkPOfhyLQtopfG6APD7vCGdB4M8_JRPs'

describe('VAPID key validation', () => {
  it('accepts a well-formed pair', () => {
    expect(publicKeyProblem(VALID_PUBLIC)).toBeNull()
    expect(privateKeyProblem(VALID_PRIVATE)).toBeNull()
  })

  it('accepts the pair web-push itself generates', () => {
    const generated = webpush.generateVAPIDKeys()
    expect(publicKeyProblem(generated.publicKey)).toBeNull()
    expect(privateKeyProblem(generated.privateKey)).toBeNull()
  })

  it('signs a real VAPID header with the pair this repo generates', () => {
    // The end-to-end proof that our encoding is the one web-push expects: if the
    // key were the wrong length or the wrong point form, this throws.
    const headers = webpush.getVapidHeaders(
      'https://fcm.googleapis.com',
      'mailto:ops@example.com',
      VALID_PUBLIC,
      VALID_PRIVATE,
      'aes128gcm'
    )
    expect(headers.Authorization).toMatch(/^vapid t=[\w-]+\.[\w-]+\.[\w-]+,\s*k=[\w-]+$/)
    // The `k` parameter IS the public key, unmodified — which is what ties a
    // signature made here to the endpoints the browser minted against it.
    expect(headers.Authorization).toContain(VALID_PUBLIC)
  })

  it('treats an absent key as absent, not as malformed', () => {
    // Push being switched off is a normal state, and must not be reported as a
    // configuration error — see the fail-closed note in vapid.ts.
    expect(publicKeyProblem(undefined)).toBeNull()
    expect(privateKeyProblem(undefined)).toBeNull()
  })

  it('rejects base64 pasted where base64url was wanted', () => {
    // The commonest real mistake: `+` and `/` decode to different bytes, so the
    // key is subtly wrong rather than obviously wrong.
    expect(publicKeyProblem(VALID_PUBLIC.replace(/_/g, '/'))).toBeTruthy()
  })

  it('rejects a truncated key', () => {
    expect(publicKeyProblem(VALID_PUBLIC.slice(0, 40))).toBeTruthy()
    expect(privateKeyProblem(VALID_PRIVATE.slice(0, 10))).toBeTruthy()
  })

  it('rejects the private key pasted into the public slot, and the reverse', () => {
    expect(publicKeyProblem(VALID_PRIVATE)).toBeTruthy()
    expect(privateKeyProblem(VALID_PUBLIC)).toBeTruthy()
  })

  it('rejects a public key that is the right length but not an uncompressed point', () => {
    // 65 bytes, but tagged 0x03 (compressed) instead of 0x04.
    const bytes = Buffer.from(VALID_PUBLIC, 'base64url')
    bytes[0] = 0x03
    expect(publicKeyProblem(bytes.toString('base64url'))).toBeTruthy()
  })
})

describe('push subscription input', () => {
  const keys = {
    p256dh: VALID_PUBLIC,
    auth: 'k8JV6sCQRcJSsN1_Tg2ZFw',
  }

  it('accepts each real push service', () => {
    for (const endpoint of [
      'https://fcm.googleapis.com/fcm/send/abcdef123456',
      'https://android.googleapis.com/gcm/send/abcdef123456',
      'https://updates.push.services.mozilla.com/wpush/v2/gAAAAAB',
      'https://web.push.apple.com/QDFwAAAA-abcdef',
      'https://notify.windows.com/w/?token=abcdef123456',
    ]) {
      expect(
        pushSubscriptionSchema.safeParse({ endpoint, keys }).success,
        `${endpoint} should be accepted`
      ).toBe(true)
    }
  })

  it('accepts a sharded sub-domain of a known service', () => {
    const endpoint = 'https://shard-7.web.push.apple.com/QDFwAAAA-abcdef'
    expect(pushSubscriptionSchema.safeParse({ endpoint, keys }).success).toBe(true)
  })

  it('refuses an internal address — the SSRF case', () => {
    for (const endpoint of [
      'https://169.254.169.254/latest/meta-data/iam/security-credentials/',
      'https://localhost:8080/internal',
      'https://10.0.0.5/admin',
      'https://metadata.google.internal/computeMetadata/v1/',
    ]) {
      expect(
        pushSubscriptionSchema.safeParse({ endpoint, keys }).success,
        `${endpoint} must be refused`
      ).toBe(false)
    }
  })

  it('refuses a look-alike host that merely ENDS with a known name', () => {
    // The label-boundary check. A bare `endsWith` would accept both of these.
    for (const endpoint of [
      'https://evil-web.push.apple.com.attacker.test/x',
      'https://notfcm.googleapis.com.evil.test/x',
    ]) {
      expect(
        pushSubscriptionSchema.safeParse({ endpoint, keys }).success,
        `${endpoint} must be refused`
      ).toBe(false)
    }
  })

  it('refuses a non-https scheme', () => {
    for (const endpoint of [
      'http://fcm.googleapis.com/fcm/send/abc',
      'file:///etc/passwd',
      'javascript:alert(1)',
    ]) {
      expect(
        pushSubscriptionSchema.safeParse({ endpoint, keys }).success,
        `${endpoint} must be refused`
      ).toBe(false)
    }
  })

  it('refuses malformed device keys rather than letting them throw in the encrypter', () => {
    const endpoint = 'https://fcm.googleapis.com/fcm/send/abcdef123456'
    expect(
      pushSubscriptionSchema.safeParse({ endpoint, keys: { ...keys, p256dh: 'short' } }).success
    ).toBe(false)
    expect(
      pushSubscriptionSchema.safeParse({ endpoint, keys: { ...keys, auth: 'has+invalid/chars' } })
        .success
    ).toBe(false)
  })

  it('needs only an endpoint to unsubscribe, and never the keys', () => {
    const parsed = pushUnsubscribeSchema.safeParse({
      endpoint: 'https://fcm.googleapis.com/fcm/send/abcdef123456',
    })
    expect(parsed.success).toBe(true)
  })
})

describe('the notification catalog', () => {
  it('emails the events that cost something to miss', () => {
    for (const event of [
      'timesheet.decided',
      'payment.decided',
      'onboarding.changes_requested',
      'visa.expiring',
    ] as const) {
      expect(importanceFor(event), `${event} should be emailed`).toBe('important')
    }
  })

  it('does NOT email the high-volume, low-stakes ones', () => {
    for (const event of ['task.assigned', 'task.commented', 'ticket.replied'] as const) {
      expect(importanceFor(event), `${event} should not be emailed`).toBe('normal')
    }
  })

  it('defaults an unknown or omitted event to quiet', () => {
    // The safety property: forgetting to add a catalog entry can never turn into
    // an accidental email to the whole company.
    expect(importanceFor(undefined)).toBe('normal')
    expect(importanceFor('generic')).toBe('normal')
  })

  it('lets an announcement override the default, in both directions', () => {
    expect(importanceFor('announcement')).toBe('normal')
    expect(importanceFor('announcement', 'important')).toBe('important')
  })

  it('sends each role to its own portal', () => {
    // A push that sends an employee to an /org path lands them on a redirect to
    // their own dashboard, having lost the thing they tapped.
    expect(pathFor('timesheet.decided', 'employee')).toBe('/employee/timesheets')
    expect(pathFor('timesheet.decided', 'org')).toBe('/org/timesheets')
    expect(pathFor('ticket.replied', 'employee')).toBe('/employee/helpdesk')
    expect(pathFor('ticket.replied', 'org')).toBe('/org/helpdesk')
  })

  it('only ever produces same-origin relative paths', () => {
    const events = [
      'announcement',
      'timesheet.decided',
      'payment.decided',
      'ticket.replied',
      'ticket.status',
      'onboarding.changes_requested',
      'task.assigned',
      'task.commented',
      'visa.expiring',
      'generic',
    ] as const

    for (const event of events) {
      for (const role of ['employee', 'org'] as const) {
        const path = pathFor(event, role)
        expect(path.startsWith('/'), `${event}/${role} must be a path`).toBe(true)
        // `//host` is a protocol-relative URL, not a path.
        expect(path.startsWith('//'), `${event}/${role} must not be protocol-relative`).toBe(false)
      }
    }
  })

  it('groups a burst on one thread, and keeps separate facts separate', () => {
    expect(tagFor('task.commented', 'task-1')).toBe('task:task-1')
    expect(tagFor('ticket.replied', 'ticket-9')).toBe('ticket:ticket-9')
    // Two timesheets being decided are two things to know about; collapsing
    // them would hide one.
    expect(tagFor('timesheet.decided', 'sheet-1')).toBeUndefined()
    expect(tagFor('task.commented', null)).toBeUndefined()
  })
})
